apiVersion: v1
kind: Service
metadata:
  name: {{ include "argus-ops.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "argus-ops.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "argus-ops.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
